FROM apache/beam_python3.12_sdk:2.66.0

RUN pip install --no-cache-dir \
    beautifulsoup4 \
    html5lib==1.1 \
    six>=1.16.0 \
    webencodings>=0.5.1 \
    pyarrow==16.1.0 \
    pandas==2.2.0 \
    numpy==1.26.4